### PR TITLE
Changes for art 3.12

### PR DESCRIPTION
**Pull request by knoepfel**

### CODE REVIEW

**Comment by knoepfel** [comment]
I adjusted the base branch from `develop` to `icarus` as these changes arose while updating sbncode.

**Comment by francois-drielsma** [comment]
Hi @knoepfel , sorry for the delay, I only learned of the existence of this PR today. Which `sbncode`/`icaruscode` version can this be tested with? The latest?

**Comment by knoepfel** [comment]
@francois-drielsma, this can be tested whenever `sbncode`/`icaruscode` upgrade to `larsoft` v09_74_00.  I don't think they've upgraded yet.

**Comment by francois-drielsma** [comment]
Ok it seems that Git is not happy with recursive merging but I don't actually see any issue when doing it manually (no actual conflict on the Supera package). I will merge this PR and try again, I think this should solve the issue.

```
Recursive merging with submodules currently only supports trivial cases.
Please manually handle the merging of each conflicted submodule.
This can be accomplished with the following steps:
 - go to submodule (sbncode/Supera), and either merge commit d3966fa
   or update to an existing commit which has merged those changes
 - come back to superproject and run:

      git add sbncode/Supera

   to record the above merge or update
 - resolve any other conflicts in the superproject
 - commit the resulting index in the superproject
```

**Pull request merged**
